#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { isHandRegistered, readCurrentSources, renderCatalog } from "./tool-spec-source.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const catalogPath = path.join(root, "src/tool-spec/catalog.ts");
const manifestPath = path.join(root, "tools/generated/tool-spec-manifest.json");
const workerCommandPath = path.join(root, "src/generated/worker-command.ts");
const policyPath = path.join(root, "tools/generated/command-safety-policy.json");
const checkOnly = process.argv.includes("--check");

const sources = readCurrentSources(root);
if (!fs.existsSync(catalogPath)) {
  if (checkOnly) {
    throw new Error(`Missing ToolSpec catalog: ${catalogPath}`);
  }
  fs.mkdirSync(path.dirname(catalogPath), { recursive: true });
  fs.writeFileSync(catalogPath, renderCatalog(sources));
}

const catalogModule = await import(pathToFileURL(catalogPath).href);
const { TOOL_SPECS: toolSpecs } = catalogModule;

function safetyProjection(safety) {
  return {
    readOnly: safety.kind === "read",
    destructive: safety.kind === "read" ? false : safety.destructive,
    confirmRequired: safety.kind !== "read" && safety.destructive,
    autoCheckpoint: safety.kind === "modelMutation",
  };
}

function manifestFromCatalog() {
  return {
    version: "1",
    tools: toolSpecs
      .filter((spec) => spec.exposure.kind === "mcp")
      .sort((left, right) => left.implementation.command.localeCompare(right.implementation.command))
      .map((spec) => {
        const exposure = spec.exposure;
        const safety = safetyProjection(spec.safety);
        return {
          name: exposure.name,
          workerCommand: spec.implementation.command,
          tier: exposure.tier,
          readOnly: safety.readOnly,
          destructive: safety.destructive,
          confirmRequired: safety.confirmRequired,
          description: exposure.description,
          ...(exposure.descriptionSource ? { descriptionSource: exposure.descriptionSource } : {}),
          tags: [...exposure.tags],
          domains: [...exposure.domains],
          schema: exposure.input.key,
        };
      }),
  };
}

function workerCommandFromCatalog() {
  const commands = [...new Set(toolSpecs.map((spec) => spec.implementation.command))].sort();
  return [
    "// Generated by npm run generate:tools. Do not edit.",
    "",
    `export const WORKER_COMMANDS = ${JSON.stringify(commands, null, 2)} as const;`,
    "",
    "export type WorkerCommand = typeof WORKER_COMMANDS[number];",
    "",
  ].join("\n");
}

function policyFromCatalog() {
  return {
    version: "1",
    source: "src/tool-spec/catalog.ts",
    commands: toolSpecs.map((spec) => {
      const implementation = spec.implementation;
      const selection =
        spec.selection.kind === "none"
          ? { kind: "none" }
          : {
              kind: "bindings",
              when: spec.selection.when,
              bindings: spec.selection.bindings.map((binding) => ({ ...binding })),
            };
      return {
        command: implementation.command,
        csharpHandler: implementation.csharpHandler,
        safety: { ...spec.safety },
        selection,
        exposure: spec.exposure.kind,
      };
    }),
  };
}

function schemaKeys(schema) {
  const definition = schema?._def;
  const shape = typeof definition?.shape === "function" ? definition.shape() : definition?.shape;
  return shape && typeof shape === "object" ? new Set(Object.keys(shape)) : null;
}

export function validateToolSpecs(specs, currentSources = sources) {
  const errors = [];
  const commands = currentSources.registryCommands.map(({ command }) => command);
  const registrySet = new Set(commands);
  const seenCommands = new Set();
  const seenNames = new Set();
  const schemaValues = new Map();
  const catalogCommands = [];

  for (const spec of specs) {
    const implementation = spec.implementation;
    const command = implementation.command;
    catalogCommands.push(command);
    if (seenCommands.has(command)) {
      errors.push(`duplicate catalog command: ${command}`);
    }
    seenCommands.add(command);
    if (!registrySet.has(command)) {
      errors.push(`catalog command missing from WorkerCommandRegistry: ${command}`);
      continue;
    }

    const registryEntry = currentSources.registryCommands.find((entry) => entry.command === command);
    if (implementation.csharpHandler !== `Program.${registryEntry.handler}`) {
      errors.push(`handler drift for ${command}: expected Program.${registryEntry.handler}`);
    }

    const expectedDestructive = currentSources.csharpDestructive.has(command);
    const declaredDestructive = spec.safety.kind === "read" ? false : spec.safety.destructive;
    if (declaredDestructive !== expectedDestructive) {
      errors.push(
        `destructive drift for ${command}: catalog=${declaredDestructive}, C#=${expectedDestructive}`,
      );
    }

    const expectedAutoCheckpoint = currentSources.csharpAutoCheckpoint.has(command);
    const declaredAutoCheckpoint = spec.safety.kind === "modelMutation";
    if (declaredAutoCheckpoint !== expectedAutoCheckpoint) {
      errors.push(
        `auto-checkpoint drift for ${command}: catalog=${declaredAutoCheckpoint}, C#=${expectedAutoCheckpoint}`,
      );
    }

    if (spec.safety.kind === "modelMutation" && spec.safety.checkpoint !== "auto") {
      errors.push(`model mutation without automatic checkpoint: ${command}`);
    }
    if (spec.safety.kind === "nonModelSideEffect") {
      if (spec.safety.checkpoint !== "notApplicable") {
        errors.push(`side effect with an applicable checkpoint: ${command}`);
      }
      if (!spec.safety.rationale.trim()) {
        errors.push(`nonModelSideEffect requires a rationale: ${command}`);
      }
    }

    if (spec.exposure.kind === "mcp") {
      if (seenNames.has(spec.exposure.name)) {
        errors.push(`duplicate MCP tool name: ${spec.exposure.name}`);
      }
      seenNames.add(spec.exposure.name);
      if (!spec.exposure.description.trim()) {
        errors.push(`MCP tool has an empty description: ${command}`);
      }
      if (!spec.exposure.input?.key || !spec.exposure.input?.value) {
        errors.push(`MCP tool has no schemaRef: ${command}`);
      } else {
        const previous = schemaValues.get(spec.exposure.input.key);
        if (previous && previous !== spec.exposure.input.value) {
          errors.push(`schema key is paired with multiple Zod objects: ${spec.exposure.input.key}`);
        }
        schemaValues.set(spec.exposure.input.key, spec.exposure.input.value);
        const keys = schemaKeys(spec.exposure.input.value);
        if (keys && spec.selection.kind === "bindings") {
          for (const binding of spec.selection.bindings) {
            if (!keys.has(binding.targetArg)) {
              errors.push(
                `selection target ${binding.targetArg} is absent from ${spec.exposure.input.key}: ${command}`,
              );
            }
          }
        }
      }
    }

    const expectedSelection = currentSources.selection[command] ?? [];
    const declaredSelection = spec.selection.kind === "bindings" ? spec.selection.bindings : [];
    if (JSON.stringify(declaredSelection) !== JSON.stringify(expectedSelection)) {
      errors.push(`selection binding drift for ${command}`);
    }
  }

  const catalogSet = new Set(catalogCommands);
  for (const command of commands) {
    if (!catalogSet.has(command)) {
      errors.push(`WorkerCommandRegistry command missing from catalog: ${command}`);
    }
  }
  for (const command of currentSources.selection ? Object.keys(currentSources.selection) : []) {
    if (!catalogSet.has(command)) {
      errors.push(`selection-bound command missing from catalog: ${command}`);
    }
  }

  const manifestCommands = new Set(
    specs
      .filter((spec) => spec.exposure.kind === "mcp")
      .map((spec) => spec.implementation.command),
  );
  for (const command of commands) {
    if (manifestCommands.has(command) === !isHandRegistered(command)) {
      continue;
    }
    errors.push(
      `exposure drift for ${command}: ${isHandRegistered(command) ? "workerOnly" : "mcp"} expected`,
    );
  }

  const confirmAndSave = specs.find(
    (spec) => spec.implementation.command === "confirm_and_save",
  );
  if (
    !confirmAndSave
    || confirmAndSave.safety.kind !== "modelMutation"
    || !confirmAndSave.safety.destructive
  ) {
    errors.push("confirm_and_save must be a destructive modelMutation");
  }

  return errors;
}

function expectedArtifacts() {
  return {
    manifest: `${JSON.stringify(manifestFromCatalog(), null, 2)}\n`,
    workerCommand: workerCommandFromCatalog(),
    policy: `${JSON.stringify(policyFromCatalog(), null, 2)}\n`,
  };
}

function writeOrCheck(filePath, expected) {
  const actual = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : "";
  if (checkOnly) {
    if (actual !== expected) {
      throw new Error(`Generated artifact drift detected: ${path.relative(root, filePath)}`);
    }
    return;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, expected);
}

async function main() {
  const diagnostics = validateToolSpecs(toolSpecs);
  if (diagnostics.length) {
    throw new Error(`ToolSpec validation failed:\n- ${diagnostics.join("\n- ")}`);
  }

  const artifacts = expectedArtifacts();
  writeOrCheck(manifestPath, artifacts.manifest);
  writeOrCheck(workerCommandPath, artifacts.workerCommand);
  writeOrCheck(policyPath, artifacts.policy);

  if (checkOnly) {
    console.log(`ToolSpec artifacts are current (${toolSpecs.length} commands)`);
  } else {
    console.log(`Generated ToolSpec artifacts (${toolSpecs.length} commands)`);
  }
}

const invokedPath = process.argv[1] ? path.resolve(process.argv[1]) : "";
if (invokedPath === path.resolve(fileURLToPath(import.meta.url))) {
  await main();
}

export {
  catalogModule,
  manifestFromCatalog,
  policyFromCatalog,
  sources,
  toolSpecs,
  workerCommandFromCatalog,
};
