using System.Text.Json;

internal static partial class Program
{
    private static Dictionary<string, Func<JsonElement?, object>> BuildCommandRegistry() =>
        new(StringComparer.Ordinal)
        {
            ["status"] = Status,
            ["open"] = Open,
            ["export"] = Export,
            ["measure"] = Measure,
            ["list_features"] = ListFeatures,
            ["inspect_document"] = InspectDocument,
            ["list_components"] = ListComponents,
            ["list_reference_geometry"] = ListReferenceGeometry,
            ["list_bom"] = ListBom,
            ["list_mates"] = ListMates,
            ["set_component_visible"] = SetComponentVisible,
            ["set_component_fixed"] = SetComponentFixed,
            ["rename_component"] = RenameComponent,
            ["mate_coord_sys"] = MateCoordSys,
            ["delete_all_mates"] = DeleteAllMates,
            ["delete_mates_in_range"] = DeleteMatesInRange,
            ["delete_mate"] = DeleteMate,
            ["unfix_all_components"] = UnfixAllComponents,
            ["set_component_configuration"] = SetComponentConfiguration,
            ["mate_component_origin"] = MateComponentOrigin,
            ["list_configurations"] = ListConfigurations,
            ["list_dimensions"] = ListDimensions,
            ["set_feature_suppression"] = SetFeatureSuppression,
            ["add_configuration_copy"] = AddConfigurationCopy,
            ["get_component_box"] = GetComponentBox,
            ["transform_component"] = TransformComponent,
            ["set_component_transform"] = SetComponentTransform,
            ["set_dimension"] = SetDimension,
            ["mate_planes"] = MatePlanes,
            ["get_feature_box"] = GetFeatureBox,
            ["mate_coincident"] = MateCoincident,
            ["mate_parallel"] = MateParallel,
            ["mate_try_coincident"] = MateTryCoincident,
            ["mate_try_parallel"] = MateTryParallel,
            ["mate_try_distance"] = MateTryDistance,
            ["mate_try_perpendicular"] = MateTryPerpendicular,
            ["mate_try_width"] = MateTryWidth,
            ["mate_distance"] = MateDistance,
            ["mate_perpendicular"] = MatePerpendicular,
            ["mate_width"] = MateWidth,
            ["mate_limit_angle"] = MateLimitAngle,
            ["debug_limit_angle"] = DebugLimitAngle,
            ["mate_probe"] = MateProbe,
            ["align_component_to_feature"] = AlignComponentToFeature,
            ["probe_feature_faces"] = ProbeFeatureFaces,
            ["get_part_feature_box"] = GetPartFeatureBox,
            ["get_planar_face_index"] = GetPlanarFaceIndex,
            ["select_face_by_ray"] = SelectFaceByRay,
            ["get_persist_reference"] = GetPersistReference,
            ["select_by_persist_reference"] = SelectByPersistReference,
            ["rebuild_document"] = RebuildDocument,
            ["ensure_offset_plane"] = EnsureOffsetPlane,
            ["reset_component_transform"] = ResetComponentTransform,
            ["insert_coord_sys"] = InsertCoordSys,
            ["list_interferences"] = ListInterferences,
            ["set_mate_suppression"] = SetMateSuppression,
            ["torso_frame_build_mates"] = TorsoFrameBuildMates,
            ["save_document"] = SaveDocument,
            ["close_all_documents"] = CloseAllDocuments,
            ["diagnose_part_save"] = DiagnosePartSave,
            ["clone_solid_body_part"] = CloneSolidBodyPart,
            ["mirror_part_file"] = MirrorPartFile,
            ["make_component_independent"] = MakeComponentIndependent,
            ["set_custom_properties"] = SetCustomProperties,
            ["replace_components_by_path"] = ReplaceComponentsByPath,
            ["replace_component_path"] = ReplaceComponentPath,
            ["layout_add_shoulder_mounts"] = LayoutAddShoulderMounts,
            ["place_shoulder_roll_motors"] = PlaceShoulderRollMotors,
            ["get_component_transform"] = GetComponentTransform,
            ["capture_shoulder_roll_golden"] = CaptureShoulderRollGolden,
            ["apply_shoulder_roll_golden"] = ApplyShoulderRollGolden,
            ["vendor_add_rs03_urdf_frame"] = VendorAddRs03UrdfFrame,
            ["insert_component"] = InsertComponent,
            ["cut_actuator_cavity"] = CutActuatorCavity,
            ["build_torso_compute_shelf"] = BuildTorsoComputeShelf,
            ["create_mallet_mount"] = CreateMalletMount,
            ["debug_mate_entities"] = DebugMateEntities,
        };
}
